### ISSUE TITLE
SMBIOS data missing from machineInventory

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-operator#110] opened 2022-08-03 09:36 UTC
Although `elemental-register --debug` shows
```yaml
...
      NoSMBIOS: false,
...
```
there's no SMBIOS data in the created `machineInventory`

```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventory
metadata:
  creationTimestamp: "2022-08-03T09:11:58Z"
  generation: 1
  managedFields:
  - apiVersion: elemental.cattle.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:tpmHash: {}
    manager: elemental-operator
    operation: Update
    time: "2022-08-03T09:11:58Z"
  - apiVersion: elemental.cattle.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:conditions: {}
        f:plan:
          .: {}
          f:checksum: {}
          f:secretRef:
            .: {}
            f:name: {}
            f:namespace: {}
    manager: elemental-operator
    operation: Update
    subresource: status
    time: "2022-08-03T09:11:58Z"
  name: m-raspberrypi-rpi-30303031-3030-3030-6130-393533306132
  namespace: fleet-default
  resourceVersion: "18822"
  uid: 6b9d3e35-7866-4e8c-94a6-8a4f3cc18a10
spec:
  tpmHash: 2d4bb87828a11cd790634d33e51cfacc9ea1cbb7937eda4e9210eed9c7410f8b
status:
  conditions:
  - lastUpdateTime: "2022-08-03T09:11:58Z"
    status: "True"
    type: Initialized
  - lastUpdateTime: "2022-08-03T09:11:58Z"
    message: waiting for plan to be applied
    status: "False"
    type: Ready
  - lastUpdateTime: "2022-08-03T09:11:58Z"
    message: waiting for plan to be applied
    status: "False"
    type: PlanReady
  plan:
    checksum: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
    secretRef:
      name: m-raspberrypi-rpi-30303031-3030-3030-6130-393533306132
      namespace: fleet-default
```

**Comment by Itxaka** [comment] 2022-08-03 09:50
SMBios data is not supposed to be stored anywhere, its used to template the name field in the inventory(https://github.com/rancher/elemental-operator/blob/main/pkg/server/register.go#L131) but never stored. In fact is it send as a header in the request: https://github.com/rancher/elemental-operator/blob/main/pkg/server/register.go#L247

**Comment by Itxaka** [comment] 2022-08-03 09:52
Closing this as its not a bug. If smbios data is wanted to be stored on the inventory please create a feature request with a clear use case for that smbios data in the inventory lifecycle.

**Closed by Itxaka** 2022-08-03 09:52 UTC
Labels: bug

**Comment by kkaempf** [comment] 2022-08-03 10:20
It was in `machineInventory` before - why was it dropped ? And what's the point in having `nosmbios` now ? 🤔

**Comment by Itxaka** [comment] 2022-08-03 10:27
I think it was dropped because it was not used anywhere and broke the default nginx deployment (max size response) due returning a huge chunk of data for no reason.

No smbios skips running dmidecode on the node, which could be broken, be slow, take a lot of time or even not present or not available to the user.

**Comment by Itxaka** [comment] 2022-08-03 10:31
Here, you even commented on it :laughing: https://github.com/rancher/elemental-operator/issues/5

**Comment by kkaempf** [comment] 2022-08-03 11:11
> Here, you even commented on it laughing #5

That's why `nosmbios: true` is the default.

**Comment by kkaempf** [comment] 2022-08-03 11:13
In general, uploading smbios data to the machineInventory has its uses, esp. for large deployments. smbios data gives you important details (number of cpu cores, main memory available, storage devices, gpu devices, etc.) to choose the right machines for a cluster for a specific job.
We might even change the default to `nosmbios:false` once #5 is fixed

**Comment by Itxaka** [comment] 2022-08-03 11:20
Sure, Im not saying its not useful. Im saying this is not a bug. If this feature is wanted we should open a card for it as it requires planning and a proper development instead of just fixing it by storing 18Kb of text in the registration and have nginx fail :D
