### ISSUE TITLE
Friendlier URLs for registration endpoint

### ISSUE THREAD

**Issue by agracey** [rancher/elemental-operator#15] opened 2022-07-05 17:03 UTC
If something goes wrong with a deployment, it would be nice to have a way to specify a nicer URL that people need to type in. This could also help with identifying which cloud-init was run when a machine registered. 

It might also be worth having a way to marking one of these as "default" to make the (maybe most common?) use case of only one registration endpoint being required.

**Comment by davidcassany** [comment] 2022-07-21 10:37
I think this is a duplicate of #73, closing, feel free to reopen if I miss understood it.

**Closed by davidcassany** 2022-07-21 10:37 UTC

**Comment by fgiudici** [comment] 2022-09-27 10:15
This is related to #186
